# Generated by Django 3.2.14 on 2022-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220818_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedoperationaltask',
            name='status',
            field=models.IntegerField(choices=[(5, 'Задачи, выполненные в срок (5)'), (10, 'Задачи выполняется в срок более 30 дней (10)'), (15, 'Выполняется (15)'), (20, 'Прогноз отставания от графика (20)'), (25, 'Неактуальная задача (25)'), (30, 'Выполнена с отсрочкой (30)'), (35, 'Просрочено, не выполнено (35)')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='archivedstrategictask',
            name='status',
            field=models.IntegerField(choices=[(5, 'Задачи, выполненные в срок (5)'), (10, 'Задачи выполняется в срок более 30 дней (10)'), (15, 'Выполняется (15)'), (20, 'Прогноз отставания от графика (20)'), (25, 'Неактуальная задача (25)'), (30, 'Выполнена с отсрочкой (30)'), (35, 'Просрочено, не выполнено (35)')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='operationaltask',
            name='status',
            field=models.IntegerField(choices=[(5, 'Задачи, выполненные в срок (5)'), (10, 'Задачи выполняется в срок более 30 дней (10)'), (15, 'Выполняется (15)'), (20, 'Прогноз отставания от графика (20)'), (25, 'Неактуальная задача (25)'), (30, 'Выполнена с отсрочкой (30)'), (35, 'Просрочено, не выполнено (35)')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='strategictask',
            name='status',
            field=models.IntegerField(choices=[(5, 'Задачи, выполненные в срок (5)'), (10, 'Задачи выполняется в срок более 30 дней (10)'), (15, 'Выполняется (15)'), (20, 'Прогноз отставания от графика (20)'), (25, 'Неактуальная задача (25)'), (30, 'Выполнена с отсрочкой (30)'), (35, 'Просрочено, не выполнено (35)')], verbose_name='Статус'),
        ),
    ]
